import "./style.css";
import "../assets/img/localisation.png";
import "../assets/img/weather.png";
import "../assets/img/nodeicon.png";
import "../assets/img/weatherapp.png";
import "../assets/img/IP.png";
import "../assets/img/ville.png";
import "../assets/img/me.jpg";
import '../assets/js/app.js'